//// GUI STYLES ////

(
~style_1 = Dictionary.newFrom([
	"header_font", Font("DIN Condensed", 32),
	"subheader_font", Font("DIN Condensed", 20),
	"text_font", Font("DIN Condensed", 16),
	"window_color", Color.fromHexString("#6F6866"),
	"top_level_frame_color", Color.fromHexString("#CDEDFD"),
	"header_frame_color", Color.fromHexString("#A9F8FB"),
	"bank_frame_color", Color.fromHexString("#B6DCFE"),
	"text_color", Color.fromHexString("#6F6866")
]);
)